# TEMP FIX FOR https://bugs.kde.org/show_bug.cgi?id=519134
#Type Name ID GECOS                  Home directory Shell
u     plasmalogin -  "PLASMALOGIN Greeter Account" /var/lib/plasmalogin   - video:render
